name: video_player_flutter_mpv
description: package:video_player support for all platforms, based on flutter_mpv.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 2.0.0
topics:
  - video
  - video-player
  - cross-platform
  - media-kit

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # NOTE: Bump before publishing to pub.dev
  flutter_mpv: ^1.2.1
  flutter_mpv_video: ^2.0.0

  universal_platform: ^1.0.0+1
  video_player_platform_interface: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

